name: lantern-xgb
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.13.12
  - pandas=2.3.3
  - lifelines=0.30.1
  - scikit-learn=1.8.0
  - scikit-optimize
  - shap=0.50.0
  - xgboost=3.2.0
  - seaborn=0.13.2
  - pyyaml=6.0.3
  - pip:
    - neuroCombat==0.2.12